//Gambar Katsuragi Keima
//Code by MONG

#include <stdio.h>
main ()

{


"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMOMNNZZ$$$$Z8NNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMZ$$$$$$$$$$$$$$$$$$$$$MMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMM$8$$7$$$$$$$$$$$$$7$$$$$$$$$$77MMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMM$Z$$$$$$$$$$$$$$$77$$$$$$$$$$$$$$$$ZNMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMDZ$$$$$$$$$7$$$$$$$$$$$$$$$$$$$$$$$$$$$$NMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMM7$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$77$MMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMND$$$$$$$7$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$77777$MMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMM8$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$7$$$$$$$$$$777ZMMMMMMMMMMMMMO \n");
"MMMMMMMMMMD?~~~$$$$$$$$$$$$$Z$$$$$$$$Z$$$$$Z$$$$$$$$$7$$$$$$7$7$MMMMMMMMMMMMO \n");
"MMMMMMMMMO=~::=7I=7$$$$$$$7$$Z$$$$$$$$$$$$$$$$$$$$$$$$7$7$77$77:IMMMMMMMMMMMO \n");
"MMMMMMMM8~:~~7?~~+=7$=I$$$$$$$7$$$7$$$$$$$$$$$$$$$7$$$$$7$$?I:=$$$7MMMMMMMMMO \n");
"MMMMMMMD~7?~I~~+I~77~~~::~=I7$$7$$77$$$$$$$$$$$$$$$7$$7?~:::=777N7$$NMMMMMMMO \n");
"MMMMMMI=7$$$$I7~~$?~~7:::::~::::::~~=+??IIIII?+=~::~I~=::~I777777N87$DMMMMMMO \n");
"MMMMMZ?7$$$Z$$7$7~~~~N~::::::~~:::::::~:::~:::::::::?:777777$$$7$MNO$ZMMMMMMO \n");
"MMMMO7$$$$$$D$$$$$D$DN~~:::::::~::+::::::::D:::~~?8$$$$$$$7$7$777NMNN7$MMMMMO \n");
"MMM$$$$$$$$N$$$$$M$NNM$$$$$$I?=+==~==++?I7$N$$$77$$M$$77$$$7$7$7$NNMNN7ZMMMMO \n");
"MMMO$$O$$$$8$$$$NZ7NNN8Z$$$$$$$O$$$8$$$77$7NO$$$$$$MZ$$7$$$$7$777NNMNNN$DMMMO \n");
"MMMZ$Z$$$ZM$$$$MM$OMNMM$Z$$$$$$N$$$ON$$$$$$NM$$$$7M8N$$$M$$$777$7NNMMNMN7NMMO \n");
"MMO$$M$$$ZNZZ$ONM$MNN?:$$$$$$$$M$$$Z=+$7$$$ONMMO$$$$MN$$OD$$$$$$$NNMMMMDN$MMO \n");
"MM$$MM$$$NZ$$$NNN$NMN~~N$$$$$$$NN$$$=~~D$ZNONMMD$$$$MNN$$MD$$$$$$NNMMMMMMN8MO \n");
"MD$$MN$Z$NZ$$ZMMMDMM~::~M$7$$$7NMZ$ZNOI,N$$$NM~MN$$$OMNN$NND$7$$$NNMMMMMMMMMO \n");
"MO$$NM$$ONO$$NNZDZN$~:=I~7$$$$$NMM$$N::..:DM8N~~NNO77MMNN$MMN$7$$NNMMMMMMMMMO \n");
"MD$ONM$$8N8Z$NN~D8N~::,.,~Z7$$$8N?8$D:??..:$MMMMMMMMMOMMMNZ$DNO$ONNMMMMMMMMMO \n");
"M7$NMM$$ZNM$ZMM8M8N:~,I,.,:Z$$$$NN:Z8~:7MMMMMMMMMMMMMNNMMMMM~NNNNNMMMMMMMMMMO \n");
"MM$NMMZ$$NNO$MM$NMMMMMM.,..:N$$$NM::$D=:?MMMMMMMMMMM?MNNMN~MMMNNNNMMMMMMMMMMO \n");
"MMMNNMD$$ONM$ZM+:.O7MMMM+...,$$$$NO:.7.. .$DDDDDDDMM~N$OMM~:~MNNNMMMMMMMMMMMO \n");
"MMODMMMM$$NND7MZ....DDNND.....,N$OM:......~8OOOOO8O.:N78ND:.8NNNMMMMMMMMMMMMO \n");
"MMMDMMMMD$$NM~N~:...?888D=.......N8I.....Z$ZZOOZ$Z:.~M7NM~.:NNNMMMMMMMMMMMMMO \n");
"MMMMMMMMMMD$MM:::,.NOZZO$8.........N=....+Z=OOZ?$N..Z8$NO..NNNMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMM8M=,,,..8IZZ=D,.Z$~:=$+~......8Z?==ZD...I$DM.?NNMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMN......8ZIZ=..,.......7......,DNZ,..$,$OM=MNNMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMNMZ......,O,..:..........7=.......~:..:NMNNNMNMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMDM,=$==~?7=.........................:MMNNNM8N8MMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMN8M...............................,?MNNMNMM8MMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMNMO~...........................:8NNMNMNMMMMNMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMNMMNZ......................:ZMNMNMNMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMM8=..............,:$MMMMNMDNMMNMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMND7=~+?$DN$7MMMMDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMM=88DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMM8MNNM~~?~::I:~=7$DDMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMM7O8888MD8~,+O...~::$$$Z$Z7MMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMM888D88M8M..~=..,:.$$$$$$$$$NNMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMDD$$$$$7N?..,.....$$$$$N8Z$$$$$DMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMM$MD$$$$Z$,..,...:$$$$ZD88$$$$$$$8MMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMM$$$D$Z8$$:.......,$$$$78D$$$ZN8OONMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMZ$$8Z$OD,:~...:...8$$$$8$N$$$$$$$NMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMD$$$$D$8:::,..,:...=7$$DM$$$$$$$$ZMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMM$$8O$OZ8$MZ...=~~...DD$D$$$O$$$$ZMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMND8$N88888M8N..8M7:.MO$$O88O$$$$$MMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMM8$$ZDDMDOZZZDZ$=D$$D$$$$N88$$$$$ZZMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMM8$$$$$$$$$$$$$$$$Z$MZ$$$M87$$$$$87DMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMM$$$$$$$$$$$$$$$$$$Z88M$DZZ$$$$$D$$MMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMN$$$$$$$ZO8888888DDND8M$$$$$$$N$$NMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMM8O888888MMMN888DDOZ$$$$$$$N$$OMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMNDDD8MND888$$$$$$$$D$$OMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMD8N88D88DND$$$$$$8N888NZDMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMD7$$$$ON$$$$$$DMMMMD8MN$$$NMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMN8OD$$$$$DD$$$$ZD8NNDD8D$$$$OMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMM88DM888Z$$OD8888D8DD8MN$$$$$$$8MMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMZOO888MMDZ$$DMD8DDD888$$$$ODDD8$Z$ZZOZ$$$$$MMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMO~:~~~87II7II777M8888D8M788$$$$$$$Z88NNNNNDZ$OMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMZ:~::::~~+OOZ7II77$88DN7+IN7D$$$$$8N=~~:::::~?DMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMN~::::::::~~:~~7D7I7I?~:~=ZI77NOZ~~:::::::::::~MMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMM8+?+::::::::::::~~+MM7MI=~ODM$I=~~~~~:::::::::$MMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMM87I$=::~:::~:::::::~~~$ZD777I+~:~~?I~~:::~:++IMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMDI~:~~?O?:~~::::~IZM777$D77=~~~:+78Z?:::~?INMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMNM7=::~~=~:~ID~$Z~I7NM$88$??IIII=:+IIDMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMDZ~::D=~~I$DDDOO$7IIIIII$8OMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMO?:~IDDDZODMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~MD8ZZZNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7$ZZZDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO$NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO \n");


}